### ISSUE TITLE
[Help] djula howto

### ISSUE THREAD

**Issue by rnfn** [mmontone/cl-forms#1]
How to use cl-form with djula? i've tried to understand it from djula test file, but i get 

> {# Error: Unknown tag FORM #} {# Error: Unknown tag FORM-START #} {# Error: Unknown tag FORM-ROW #} {# Error: Unknown tag FORM-ROW #} {# Error: Unknown tag FORM-ROW #} {# Error: Unknown tag FORM-ROW #} {# Error: Unknown tag FORM-END #}

Thank you.

**Comment by mmontone** [comment]
Have you loaded :cl-forms.djula ?

**Comment by rnfn** [comment]
> Have you loaded :cl-forms.djula ?

Sorry, I have not ~_~ 
But, after I have load :cl-forms.djula now i get another error:

`{# Error: There was an error rendering the token (TAG FORM-ROW FORM USERNAME) : Field USERNAME not found in #<FORM LOGIN-FORM /login {1003DDD303}> #}.`

this is the template:

`{% form form %}

{% form-start form %}
{% form-row form username %}
{% form-row form password %}
{% form-row form submit %}
{% form-end form %}`

this is the test file:

`(defparameter +test-form+
  (djula:compile-template*
   (asdf:system-relative-pathname :cl-microblog "templates/testform.html")))

(forms:defform login-form (:action "/login" )
  ((username :string :value "")
   (password :password :value "")
   (submit :submit :label "Sign In")))

(defroute "/testform" ()
  (let ((form (forms::get-form 'login-form)))
    (djula:render-template* +test-form+ nil :form form)))`

I'm sure I have missing something obvious here.

**Comment by rnfn** [comment]
> Can you try adding {% set-package :cl-microblog %} at the top of your testform.html template? (or set the package in which the form is defined, instead of :cl-microblog)

Thank you, that fix it. 

But, now I'm  having trouble with handle-request, I"m using Caveman, and this is the handler:

`(defroute ("/testform" :method :post) ()
  (let ((form (forms:get-form 'login-form)))
    (forms::handle-request form)
    (forms::validate-form form) ...... ))`

forms::handle-request form generate this error:

`The value
  #<FLEXI-STREAMS:FLEXI-IO-STREAM {1003D85663}>
is not of type
  SEQUENCE
   [Condition of type TYPE-ERROR]

Restarts:
 0: [ABORT] abort thread (#<THREAD "hunchentoot-worker-127.0.0.1:35444" RUNNING {1003BBF8A3}>)

Backtrace:
  0: (LENGTH #<FLEXI-STREAMS:FLEXI-IO-STREAM {1003D85663}>)
  1: (CL-PPCRE:SPLIT #<CLOSURE (LAMBDA (STRING CL-PPCRE::START CL-PPCRE::END) :IN CL-PPCRE::CREATE-SCANNER-AUX) {10079E7C8B}> #<FLEXI-STREAMS:FLEXI-IO-STREAM {1003D85663}> :START 0 :END #<unavailable argum..
  2: (HUNCHENTOOT::MAYBE-READ-POST-PARAMETERS :REQUEST #<HUNCHENTOOT:REQUEST {1003D81E13}> :FORCE T :EXTERNAL-FORMAT NIL)
.....`

I'm sorry if i keep on bothering you, thank you for your help.

**Comment by mmontone** [comment]
Hi. I don't have access to a computer now. But I implemented cl forms on hanchentoot. No explicit caveman support

**Comment by rnfn** [comment]
Ok, thank you for your help. I'll try to dig deeper.
