### ISSUE TITLE
cl-forms broken for Quicklisp

### ISSUE THREAD

**Issue by brown** [mmontone/cl-forms#13]
SBCL cannot compile system cl-forms.demo because of a bad type declaration.  Here's a Quicklisp failure log: 
 http://report.quicklisp.org/2023-11-06/failure-report/cl-forms.html#cl-forms.demo

The following pull request fixes the problem:  https://github.com/mmontone/cl-forms/pull/12

**Comment by mmontone** [comment]
Merged. Thanks!
