### ISSUE TITLE
Failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [mmontone/cl-forms#3]
Building with SBCL 2.0.9.5-442f54894 / ASDF 3.3.1 for quicklisp dist creation.

Commit id f2e4b7ec6e7c7dd9e20059c75e8fcbd1558775ac

*cl-forms.peppol* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A50103}>: Component #:PEPPOL not found, required by #<SYSTEM "cl-forms.peppol">

```

[Full log here](http://report.quicklisp.org/2020-10-06/failure-report/cl-forms.html)

**Comment by quicklisp** [comment]
Getting this now: 
```
; caught ERROR:
;   READ error during COMPILE-FILE: Symbol "ISO 4217 Currency codes" not found in the PEPPOL/CODE-LISTS package. Line: 75, Column: 63, File-Position: 2666 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/cl-forms/9d24559d3984b60d0b534a34d354939dc2d855a2/cl-forms-20201009-git/src/peppol.lisp" {10094185D3}>
```

**Comment by mmontone** [comment]
Oh. Mm. Sorry. Will check.

**Comment by mmontone** [comment]
It's odd it compiles fine locally. Checking ...

**Comment by mmontone** [comment]
It must be the fasl cache.

**Comment by mmontone** [comment]
I don't have that error, compiles fine.

But changed things so that I'm accessing the symbol with '::', not assuming it is exported, although it should.

Compiles now? Can you try again?

**Comment by mmontone** [comment]
No. I'm not being able to make it fail, and no warnings show up for me :)

Yes, it must be the way I'm loading the code lists.

```lisp
:perform (asdf:compile-op
            :after (o c)
            (dolist (code-list-file (uiop:directory-files (asdf:system-relative-pathname :peppol "code-lists/*.lisp")))
              (load code-list-file))))
```

I think I'm just going to hard code them in the asdf.

**Comment by mmontone** [comment]
Although I see I'm calling `load` there, instead of `compile-file`.

**Comment by mmontone** [comment]
I've hardcoded the code lists in the ASDF definition. Can you try again after pulling from cl-peppol?

**Comment by quicklisp** [comment]
All is good now, thanks!
