### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [mmontone/cl-forms#4]
Building with SBCL 2.1.7.62-417920f09 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id d7a116f8600d1ddb5a3753e4804c4a4228b9bd04

*cl-forms.demo* fails to build with the following error:

```
; caught ERROR:
;   during macroexpansion of (CHECK-TYPE #:FORM0 (QUOTE FORM)). Use *BREAK-ON-SIGNALS* to intercept.
;    Quoted type specifier in CHECK-TYPE: (QUOTE FORM)
;   See also:
;     The ANSI Standard, Macro CHECK-TYPE
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BF0103}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "cl-forms.demo" "test" "demo-tests" "models">

```

[Full log here](http://report.quicklisp.org/2021-09-22/failure-report/cl-forms.html)

**Comment by mmontone** [comment]
Sorry about that. Thanks for the report! Fix pushed.
